/**
 * Claude Sonnet 4.6 wrappers used by the AI Video Studio engine.
 *
 *   - generateInitialStoryboard  → builds the 360° storyboard JSON for
 *     the entire video before chunk 1 starts.
 *   - generatePerPartJsonPrompt  → produces the spec's JsonVideoPrompt
 *     for one part with full continuity context.
 *   - summarizeChunkAfterGeneration → 2-3 sentence post-hoc recap of
 *     what actually happened (used as memory for the next part).
 *   - updateStoryboardForNextPart → Claude updates the storyboard's
 *     "current state" block based on what really got generated.
 *
 * All four delegate to the existing `generateJson` helper in routes/ai/llm
 * so they inherit the same retry / validate / token-budget logic the rest
 * of the app already trusts.
 */

import { z } from "zod";
import { generateJson } from "../../routes/ai/llm";
import type {
  EngineModel,
  JsonVideoPrompt,
  NormalizedStory,
  VisualBible,
} from "../types";

/* ---------------- Storyboard ---------------- */

/**
 * Loose pre-schema that accepts the most common Claude shape drifts and
 * normalizes them into the canonical { beats, globalRules } shape. This
 * is what we hand to `generateJson` so a tiny shape variance (e.g. Claude
 * wrapping the response in { storyboard: {...} } or naming the array
 * "shots" / "scenes") never costs the user a full retry.
 */
const StoryboardBeatSchema = z.object({
  partNumber: z.coerce.number(),
  timeRange: z.string(),
  summary: z.string(),
  cameraIntent: z.string().default(""),
  mood: z.string().default(""),
});

const RawStoryboardSchema = z
  .object({
    beats: z.array(z.unknown()).optional(),
    shots: z.array(z.unknown()).optional(),
    scenes: z.array(z.unknown()).optional(),
    parts: z.array(z.unknown()).optional(),
    storyboard: z.unknown().optional(),
    globalRules: z.array(z.string()).optional(),
    rules: z.array(z.string()).optional(),
    continuityRules: z.array(z.string()).optional(),
  })
  .passthrough()
  .transform((raw) => {
    // Unwrap { storyboard: {...} } wrapper if present.
    const inner =
      raw.storyboard && typeof raw.storyboard === "object"
        ? (raw.storyboard as Record<string, unknown>)
        : (raw as unknown as Record<string, unknown>);

    const beatsRaw =
      (inner.beats as unknown[]) ??
      (inner.shots as unknown[]) ??
      (inner.scenes as unknown[]) ??
      (inner.parts as unknown[]) ??
      [];

    const beats = beatsRaw
      .map((b, idx) => {
        const o = (b ?? {}) as Record<string, unknown>;
        return {
          partNumber:
            o.partNumber ?? o.part ?? o.shotNumber ?? o.sceneNumber ?? idx + 1,
          timeRange: o.timeRange ?? o.time_range ?? o.range ?? "",
          summary: o.summary ?? o.description ?? o.shot ?? o.action ?? "",
          cameraIntent:
            o.cameraIntent ?? o.camera ?? o.cinematography ?? o.framing ?? "",
          mood: o.mood ?? o.tone ?? o.emotion ?? "",
        };
      })
      .map((b) => StoryboardBeatSchema.parse(b));

    const globalRules =
      (inner.globalRules as string[]) ??
      (inner.rules as string[]) ??
      (inner.continuityRules as string[]) ??
      [];

    return { beats, globalRules };
  });

const StoryboardSchema = RawStoryboardSchema.pipe(
  z.object({
    beats: z.array(StoryboardBeatSchema).min(1),
    globalRules: z.array(z.string()),
  }),
);

export type Storyboard = z.infer<typeof StoryboardSchema>;

const STORYBOARD_SYSTEM = `You are a senior cinematic director planning a single short film that will be generated by an AI video model in fixed-length cinematic segments.

You will be told the exact chunk plan (N parts of either 8 seconds or 15 seconds each). For every part produce ONE entry inside a "beats" array with EXACTLY these fields:

- partNumber (number, 1-indexed)
- timeRange (string, e.g. "00:00-00:08" for 8s chunks or "00:00-00:15" for 15s chunks)
- summary (string, one-sentence shot description tied to the story beat)
- cameraIntent (string, lens / movement / framing for that part)
- mood (string, emotional tone)

Also produce a "globalRules" array of 3-7 strict continuity rules (strings) that must hold across every chunk (character look, world style, lighting palette, edit grammar). The downstream prompt writer follows these LITERALLY.

OUTPUT SHAPE — return EXACTLY this top-level JSON object, no extra wrapper, no prose, no markdown fences:

{
  "beats": [ { "partNumber": 1, "timeRange": "00:00-00:08", "summary": "...", "cameraIntent": "...", "mood": "..." }, ... ],
  "globalRules": [ "...", "...", "..." ]
}

CRITICAL: this storyboard becomes the single source of truth for chunk-by-chunk prompt generation. Be precise, visual, and consistent. Return JSON ONLY.`;

export async function generateInitialStoryboard(args: {
  normalizedStory: NormalizedStory;
  visualBibleSummary: string;
  totalParts: number;
  durationSeconds: number;
  engineModel: EngineModel;
}): Promise<Storyboard> {
  const chunkSeconds = args.engineModel === "cont_pro" ? 8 : 15;
  const userPrompt = `Plan the storyboard for this video.

STORY:
${describeStory(args.normalizedStory)}

VISUAL BIBLE LOCKS:
${args.visualBibleSummary}

CHUNK PLAN: ${args.totalParts} parts of ${chunkSeconds} seconds each (total ${args.durationSeconds}s).
Engine: ${
    args.engineModel === "cont_pro"
      ? "Cont Pro — 8-second photoreal cinematic clips, image-to-video conditioning between parts."
      : "Cont Ultra — 15-second photoreal cinematic clips generated in a single call per part, image-to-video conditioning between parts. Plan each shot to BREATHE for a full 15 seconds (more sustained action, longer beats, more nuanced camera moves) — DO NOT pack 15s parts with the same density you would use for 8s parts."
  }

Return JSON in the schema described in the system prompt.`;

  return generateJson({
    systemPrompt: STORYBOARD_SYSTEM,
    userPrompt,
    schema: StoryboardSchema,
    label: "video-studio-storyboard",
    prependMasterContext: false,
  });
}

/* ---------------- Per-part JSON prompt ---------------- */

/**
 * Lenient JSON video prompt schema. Every string defaults to "" and
 * every array defaults to [] so a single missing nested field from
 * Claude does NOT kill the whole generation. The engine already
 * force-corrects the structural fields (partNumber, totalParts,
 * timeRange, engineModel, continuity flags) post-parse, so what we
 * really need from the model is the visual / direction / audio prose.
 */
// `.catch(default)` is strictly more lenient than `.default(default)`:
// `.default` only applies when a field is missing/undefined, but
// `.catch` ALSO applies when the field is present but has the wrong
// type (e.g. an array where we expect a string, or a string where we
// expect an array). Claude occasionally returns shapes like
// `negativePrompt: "no jump cut, no face change"` (string) or
// `keyFrames: { "0s": "..." }` (object) instead of arrays — those
// used to surface as "the AI returned an unexpected shape" and kill
// the whole job. With `.catch` the bad field becomes its default and
// generation continues; the engine's force-correct pass fixes the
// structural fields we care most about (partNumber, engineModel,
// continuity flags) regardless.
const s = (def = "") => z.string().catch(def);
// Coerce strings to arrays of one if Claude collapses a list into a
// single comma-separated line, otherwise fall back to []. Avoids the
// silent "negativePrompt becomes empty" trap when the model returns
// a natural-language string.
const sa = () =>
  z
    .union([
      z.array(z.string()),
      z.string().transform((v) =>
        v
          .split(/[,;|]\s*|\n+/)
          .map((s2) => s2.trim())
          .filter((s2) => s2.length > 0),
      ),
    ])
    .catch([]);
const sb = (def = false) => z.boolean().catch(def);
const sn = (def = 0) => z.coerce.number().catch(def);

const JsonVideoPromptSchema = z
  .object({
    // Accept any string and normalize downstream — Claude sometimes
    // returns "Cont Pro", "ContPro", or even the friendly label
    // instead of the snake_case slug. The engine's force-correct
    // pass overwrites this from the request anyway, but a strict
    // enum was killing the whole parse on a field we don't trust.
    engineModel: z.string().catch("cont_pro"),
    partNumber: sn(1),
    totalParts: sn(1),
    timeRange: s(),
    storyContext: z
      .object({
        title: s(),
        fullStorySummary: s(),
        currentBeat: s(),
        previousBeat: s(),
        nextBeat: s(),
      })
      .partial()
      .catch({}),
    continuity: z
      .object({
        startMode: z.string().catch("opening_frame"),
        previousLastFrameObjectPath: z.string().nullable().catch(null),
        mustStartFromPreviousFrame: sb(false),
        characterContinuityRules: sa(),
        sceneContinuityRules: sa(),
      })
      .partial()
      .catch({}),
    visualStoryboard: z
      .object({
        startingFramePrompt: s(),
        endingFramePrompt: s(),
        keyFrames: z
          .array(
            z
              .object({
                timestamp: s(),
                description: s(),
                camera: s(),
                characterPose: s(),
                environment: s(),
              })
              .partial(),
          )
          .catch([]),
      })
      .partial()
      .catch({}),
    videoDirection: z
      .object({
        mainAction: s(),
        cameraMovement: s(),
        lens: s(),
        composition: s(),
        lighting: s(),
        atmosphere: s(),
        physics: s(),
        motionRules: sa(),
      })
      .partial()
      .catch({}),
    cutSceneRules: z
      .object({
        allowed: sb(false),
        cutStyle: s(),
        mustFeelContinuous: sb(true),
        cutPurpose: s(),
      })
      .partial()
      .catch({}),
    audio: z
      .object({
        voiceoverLanguage: s(),
        voiceoverText: s(),
        voiceoverTone: s(),
        soundEffects: sa(),
        backgroundMusic: z
          .object({
            style: s(),
            tempo: s(),
            instruments: s(),
            energy: s(),
          })
          .partial()
          .catch({}),
      })
      .partial()
      .catch({}),
    negativePrompt: sa(),
    endStateForNextPart: z
      .object({
        lastFrameDescription: s(),
        characterPosition: s(),
        cameraAngle: s(),
        lightingState: s(),
        emotionState: s(),
        environmentState: s(),
      })
      .partial()
      .catch({}),
  })
  .passthrough()
  .transform((raw) => {
    // Normalize engineModel back to the snake_case enum the engine
    // expects. Accept any case, hyphen, space, etc. — anything that
    // isn't recognized falls through to "cont_pro" (the engine's
    // force-correct pass overrides this from the request anyway).
    const normEngine = (() => {
      const v = String(raw.engineModel ?? "")
        .toLowerCase()
        .replace(/[\s\-]+/g, "_");
      if (v === "cont_ultra" || v === "contultra") return "cont_ultra";
      return "cont_pro";
    })();
    // Re-fill the deeply nested defaults so downstream code never
    // touches `undefined`. Zod's `.default({})` only fills the top
    // level; the inner `.partial()` lets nested fields be missing.
    return {
      engineModel: normEngine,
      partNumber: raw.partNumber ?? 1,
      totalParts: raw.totalParts ?? 1,
      timeRange: raw.timeRange ?? "",
      storyContext: {
        title: raw.storyContext?.title ?? "",
        fullStorySummary: raw.storyContext?.fullStorySummary ?? "",
        currentBeat: raw.storyContext?.currentBeat ?? "",
        previousBeat: raw.storyContext?.previousBeat ?? "",
        nextBeat: raw.storyContext?.nextBeat ?? "",
      },
      continuity: {
        startMode: raw.continuity?.startMode ?? "opening_frame",
        previousLastFrameObjectPath:
          raw.continuity?.previousLastFrameObjectPath ?? null,
        mustStartFromPreviousFrame:
          raw.continuity?.mustStartFromPreviousFrame ?? false,
        characterContinuityRules:
          raw.continuity?.characterContinuityRules ?? [],
        sceneContinuityRules: raw.continuity?.sceneContinuityRules ?? [],
      },
      visualStoryboard: {
        startingFramePrompt: raw.visualStoryboard?.startingFramePrompt ?? "",
        endingFramePrompt: raw.visualStoryboard?.endingFramePrompt ?? "",
        keyFrames: (raw.visualStoryboard?.keyFrames ?? []).map((k) => ({
          timestamp: k?.timestamp ?? "",
          description: k?.description ?? "",
          camera: k?.camera ?? "",
          characterPose: k?.characterPose ?? "",
          environment: k?.environment ?? "",
        })),
      },
      videoDirection: {
        mainAction: raw.videoDirection?.mainAction ?? "",
        cameraMovement: raw.videoDirection?.cameraMovement ?? "",
        lens: raw.videoDirection?.lens ?? "",
        composition: raw.videoDirection?.composition ?? "",
        lighting: raw.videoDirection?.lighting ?? "",
        atmosphere: raw.videoDirection?.atmosphere ?? "",
        physics: raw.videoDirection?.physics ?? "",
        motionRules: raw.videoDirection?.motionRules ?? [],
      },
      cutSceneRules: {
        allowed: raw.cutSceneRules?.allowed ?? false,
        cutStyle: raw.cutSceneRules?.cutStyle ?? "",
        mustFeelContinuous: raw.cutSceneRules?.mustFeelContinuous ?? true,
        cutPurpose: raw.cutSceneRules?.cutPurpose ?? "",
      },
      audio: {
        voiceoverLanguage: raw.audio?.voiceoverLanguage ?? "",
        voiceoverText: raw.audio?.voiceoverText ?? "",
        voiceoverTone: raw.audio?.voiceoverTone ?? "",
        soundEffects: raw.audio?.soundEffects ?? [],
        backgroundMusic: {
          style: raw.audio?.backgroundMusic?.style ?? "",
          tempo: raw.audio?.backgroundMusic?.tempo ?? "",
          instruments: raw.audio?.backgroundMusic?.instruments ?? "",
          energy: raw.audio?.backgroundMusic?.energy ?? "",
        },
      },
      negativePrompt: raw.negativePrompt ?? [],
      endStateForNextPart: {
        lastFrameDescription:
          raw.endStateForNextPart?.lastFrameDescription ?? "",
        characterPosition: raw.endStateForNextPart?.characterPosition ?? "",
        cameraAngle: raw.endStateForNextPart?.cameraAngle ?? "",
        lightingState: raw.endStateForNextPart?.lightingState ?? "",
        emotionState: raw.endStateForNextPart?.emotionState ?? "",
        environmentState: raw.endStateForNextPart?.environmentState ?? "",
      },
    };
  });

const JSON_PROMPT_SYSTEM = `You write per-part JSON video prompts for an AI Video Studio that generates one cinematic clip at a time and stitches them into a single film. Each clip is either 8 seconds (engineModel = cont_pro) or 15 seconds (engineModel = cont_ultra) — you are told which one in the user message.

Your output is a STRICT JSON object with this top-level shape:
- engineModel ("cont_pro" | "cont_ultra")
- partNumber, totalParts, timeRange
- storyContext (full memory of the story so the model never drifts)
- continuity (whether THIS part must start from the previous chunk's REAL captured last frame; rules to keep characters and environment locked)
- visualStoryboard (starting frame prompt, ending frame prompt, 3-5 keyFrames for 8s shots / 5-8 keyFrames for 15s shots, at sub-second timestamps)
- videoDirection (mainAction, cameraMovement, lens, composition, lighting, atmosphere, physics, motionRules)
- cutSceneRules (whether a cut is allowed inside this shot — usually false; if true, it must feel continuous)
- audio (voiceoverLanguage / voiceoverText / voiceoverTone, soundEffects, backgroundMusic)
- negativePrompt (anti-drift cues — e.g. "no character face change", "no different outfit", "no jump cut")
- endStateForNextPart (the EXACT physical/emotional state you expect this part to leave the world in, so the next part can pick up from there)

Hard rules:
1. If continuity.startMode == "previous_last_frame" the visualStoryboard.startingFramePrompt MUST describe the EXACT previous-frame composition — same character pose, same camera angle, same lighting state. The model will be fed the literal PNG so the wording is for human / next-part-LLM continuity, not for the diffusion model alone.
2. characterContinuityRules and sceneContinuityRules MUST repeat the visual bible's locked descriptions verbatim (same hair, same outfit, same environment).
3. negativePrompt MUST contain at minimum "character face change", "outfit change", "wardrobe change", "world style change", "abrupt cut".
4. audio.voiceoverText must be in the requested language; if voiceover is disabled, set it to an empty string.
5. Return JSON only — no prose, no markdown, no commentary.`;

export interface PerPartPromptArgs {
  normalizedStory: NormalizedStory;
  visualBible: VisualBible;
  storyboard: Storyboard;
  partNumber: number;
  totalParts: number;
  timeRange: string;
  engineModel: EngineModel;
  voiceoverEnabled: boolean;
  voiceoverLanguage: string | null;
  bgmEnabled: boolean;
  /** Empty for part 1, otherwise the previous chunk summary. */
  previousChunkSummary: string;
  /** Object path of the captured previous last frame (null for part 1). */
  previousLastFrameObjectPath: string | null;
  /** Last part's JSON prompt for continuity (null for part 1). */
  previousJsonPrompt: JsonVideoPrompt | null;
}

export async function generatePerPartJsonPrompt(
  args: PerPartPromptArgs,
): Promise<JsonVideoPrompt> {
  const beat = args.storyboard.beats.find(
    (b) => b.partNumber === args.partNumber,
  );
  const chunkSeconds = args.engineModel === "cont_pro" ? 8 : 15;
  const userPrompt = `Generate the JSON video prompt for ONE part of a multi-part film.

PART: ${args.partNumber} of ${args.totalParts} (timeRange: ${args.timeRange})
ENGINE: ${args.engineModel} — ${chunkSeconds}-second single-call cinematic shot
ASPECT: cinematic ${chunkSeconds}-second shot${
    chunkSeconds === 15
      ? " — pace the action so it sustains for the FULL 15 seconds (longer holds, more nuanced camera moves, breathing room between beats); the voiceoverText, sound design and music must also fill 15 seconds, not 8"
      : ""
  }

STORY:
${describeStory(args.normalizedStory)}

VISUAL BIBLE LOCKS (must be repeated verbatim in every continuity rule):
${describeVisualBible(args.visualBible)}

GLOBAL RULES (storyboard):
${args.storyboard.globalRules.map((r, i) => `${i + 1}. ${r}`).join("\n")}

THIS PART'S BEAT (from storyboard):
${beat ? `summary: ${beat.summary}\ncameraIntent: ${beat.cameraIntent}\nmood: ${beat.mood}` : "(no specific beat — use the closest in the storyboard)"}

PREVIOUS PART RECAP (memory):
${args.previousChunkSummary || "(none — this is part 1)"}

PREVIOUS LAST FRAME REFERENCE: ${args.previousLastFrameObjectPath ?? "(none — this is the opening shot)"}

CONTINUITY MODE: ${args.partNumber === 1 ? "opening_frame" : "previous_last_frame"}

AUDIO TOGGLES:
- voiceover ${args.voiceoverEnabled ? `ENABLED (language: ${args.voiceoverLanguage ?? "english"})` : "DISABLED"}
- background music ${args.bgmEnabled ? "ENABLED" : "DISABLED"}

Return JSON ONLY in the schema described above.`;

  const result = await generateJson({
    systemPrompt: JSON_PROMPT_SYSTEM,
    userPrompt,
    schema: JsonVideoPromptSchema,
    label: "video-studio-json-prompt",
    prependMasterContext: false,
  });

  // Force-correct fields the model loves to drift on.
  result.partNumber = args.partNumber;
  result.totalParts = args.totalParts;
  result.timeRange = args.timeRange;
  result.engineModel = args.engineModel;
  result.continuity.previousLastFrameObjectPath = args.previousLastFrameObjectPath;
  result.continuity.startMode =
    args.partNumber === 1 ? "opening_frame" : "previous_last_frame";
  result.continuity.mustStartFromPreviousFrame = args.partNumber > 1;
  return result as JsonVideoPrompt;
}

/* ---------------- Post-chunk summary ---------------- */

const SummarySchema = z.object({
  summary: z.string(),
});

const SUMMARY_SYSTEM = `You are an editor watching one short cinematic clip (8s or 15s depending on the engine) of a multi-part film and writing a 2-3 sentence factual recap of what visually happened — characters present, what they did, where they ended up, lighting state, emotion. The recap is the MEMORY the next-part prompt writer reads, so be precise and visual. Return JSON only: {"summary": "..."}.`;

export async function summarizeChunkAfterGeneration(args: {
  jsonPrompt: JsonVideoPrompt;
  partNumber: number;
}): Promise<string> {
  const userPrompt = `Write a 2-3 sentence visual recap of part ${args.partNumber}.

What was supposed to happen (from the part's JSON prompt):
- mainAction: ${args.jsonPrompt.videoDirection.mainAction}
- camera: ${args.jsonPrompt.videoDirection.cameraMovement}
- lighting: ${args.jsonPrompt.videoDirection.lighting}
- atmosphere: ${args.jsonPrompt.videoDirection.atmosphere}

Expected end state:
- last frame: ${args.jsonPrompt.endStateForNextPart.lastFrameDescription}
- character position: ${args.jsonPrompt.endStateForNextPart.characterPosition}
- camera angle: ${args.jsonPrompt.endStateForNextPart.cameraAngle}
- lighting: ${args.jsonPrompt.endStateForNextPart.lightingState}
- emotion: ${args.jsonPrompt.endStateForNextPart.emotionState}

Return JSON: {"summary":"..."}.`;

  const out = await generateJson({
    systemPrompt: SUMMARY_SYSTEM,
    userPrompt,
    schema: SummarySchema,
    label: "video-studio-chunk-summary",
    prependMasterContext: false,
  });
  return out.summary;
}

/* ---------------- helpers ---------------- */

function describeStory(s: NormalizedStory): string {
  return [
    `Title: ${s.title}`,
    `Logline: ${s.logline}`,
    `Visual style: ${s.visualStyle}`,
    `Mood / VO tone: ${s.voiceoverTone}`,
    `BGM style: ${s.bgmStyle}`,
    `Language: ${s.language}`,
    "",
    "Characters:",
    ...s.characters.map((c) => `- ${c.name}: ${c.continuityLock}`),
    "",
    "Locations:",
    ...s.locations.map((l) => `- ${l.name}: ${l.continuityLock}`),
    "",
    "Story beats:",
    ...s.storyBeats.map(
      (b) =>
        `Beat ${b.beatNumber}: ${b.summary} (visualPurpose: ${b.visualPurpose})`,
    ),
  ].join("\n");
}

function describeVisualBible(b: VisualBible): string {
  return [
    `Style lock: ${b.styleLock.visualStyle} | grade: ${b.styleLock.colorGrade} | camera: ${b.styleLock.cameraLanguage}`,
    `Quality rules: ${b.styleLock.qualityRules.join("; ")}`,
    "",
    "Character locks:",
    ...b.characters.map(
      (c) =>
        `- ${c.name}: face=${c.faceLock} | outfit=${c.outfitLock} | DO NOT: ${c.negativeRules.join(", ")}`,
    ),
    "",
    "Location locks:",
    ...b.locations.map(
      (l) =>
        `- ${l.name}: env=${l.environmentLock} | lighting=${l.lightingLock}`,
    ),
  ].join("\n");
}
