/**
 * Live adapter smoke test — calls the real Cont Pro (Magnific Veo 3.1
 * I2V), Cont Ultra (Magnific Seedance I2V) AND Nano Banana Pro
 * (Magnific text-to-image) adapters in parallel with a minimal prompt
 * and a tiny PNG starting frame. Prints the resulting object paths
 * (or detailed error) for each so we can confirm all three pipelines
 * are reachable and accept our request shape end-to-end.
 *
 * Usage:
 *   pnpm --filter @workspace/api-server exec tsx scripts/liveAdapterTest.mts
 *
 * Costs a single 8s Veo clip + a single 5s Seedance clip + a single
 * Nano Banana Pro 2K image — small but non-zero. Skips Object Storage
 * cleanup on purpose so you can inspect the resulting assets in the
 * Library if the test passes.
 */

import { generateContProClip } from "../src/video/providers/contProAdapter.ts";
import { generateContUltraClip } from "../src/video/providers/contUltraAdapter.ts";
import { generateNanoBananaFrame } from "../src/video/providers/nanoBananaAdapter.ts";
import { readFile } from "node:fs/promises";

// Real 1280x720 PNG generated by ffmpeg (proper dimensions so Freepik
// won't reject on min-size validation). Loaded once at boot.
const TINY_PNG_B64 = (await readFile("/tmp/test_frame.png")).toString("base64");

const SAMPLE_PROMPT =
  "[CINEMATIC SHOT — Part 1/1, 0-5s] A wide cinematic establishing shot " +
  "of an empty modern art gallery at dawn. Soft golden light enters " +
  "through tall floor-to-ceiling windows. Slow dolly-in toward the " +
  "central marble pedestal. Photoreal, 35mm lens, shallow depth of field, " +
  "no people, no text overlay, no logo.";

const NEGATIVE = "watermark, logo, subtitles, distorted faces, low resolution";

async function runContPro() {
  console.log("[ContPro] starting…");
  const t = Date.now();
  try {
    const out = await generateContProClip({
      prompt: SAMPLE_PROMPT,
      negativePrompt: NEGATIVE,
      aspectRatio: "16:9",
      durationSeconds: 8,
      quality: "standard",
      startingFrame: { b64: TINY_PNG_B64, mimeType: "image/png" },
    });
    console.log(
      `[ContPro] OK in ${Math.round((Date.now() - t) / 1000)}s →`,
      out.videoObjectPath,
    );
  } catch (err) {
    console.error(
      `[ContPro] FAIL in ${Math.round((Date.now() - t) / 1000)}s →`,
      (err as Error).message,
    );
    if ((err as Error).stack) console.error((err as Error).stack);
  }
}

async function runContUltra() {
  console.log("[ContUltra] starting…");
  const t = Date.now();
  try {
    const out = await generateContUltraClip({
      prompt: SAMPLE_PROMPT,
      negativePrompt: NEGATIVE,
      aspectRatio: "16:9",
      durationSeconds: 5,
      quality: "standard",
      startingFrame: { b64: TINY_PNG_B64, mimeType: "image/png" },
    });
    console.log(
      `[ContUltra] OK in ${Math.round((Date.now() - t) / 1000)}s →`,
      out.videoObjectPath,
    );
  } catch (err) {
    console.error(
      `[ContUltra] FAIL in ${Math.round((Date.now() - t) / 1000)}s →`,
      (err as Error).message,
    );
    if ((err as Error).stack) console.error((err as Error).stack);
  }
}

async function runNanoBananaPro() {
  console.log("[NanoBananaPro] starting…");
  const t = Date.now();
  try {
    const out = await generateNanoBananaFrame({
      prompt:
        "A photoreal cinematic establishing shot of an empty modern art " +
        "gallery at dawn, soft golden light through tall windows, marble " +
        "pedestal in the center, no people, no text, no logo. Shot on " +
        "35mm, shallow depth of field.",
      aspectRatio: "16:9",
    });
    console.log(
      `[NanoBananaPro] OK in ${Math.round((Date.now() - t) / 1000)}s →`,
      out.objectPath,
      `(${out.b64.length} b64 chars, ${out.mimeType})`,
    );
  } catch (err) {
    console.error(
      `[NanoBananaPro] FAIL in ${Math.round((Date.now() - t) / 1000)}s →`,
      (err as Error).message,
    );
    if ((err as Error).stack) console.error((err as Error).stack);
  }
}

await Promise.all([runNanoBananaPro(), runContPro(), runContUltra()]);
console.log("done.");
process.exit(0);
